kafka1:
  image: spotify/kafka
  ports:
    - "2181:2181" 
    - "9092:9092"
  environment:
    ADVERTISED_HOST: 192.168.30.191
    ADVERTISED_PORT: 9092

esearch:
  image: lucasko/elasticsearch
  user: elsearch
  ports:
    - "29200:9200" 
    - "29300:9300" 
  restart: always

logstash1:
  image: logstash
  links:
    - kafka1
  volumes:
    - $PWD/logstash-config:/config-dir
  command: -f "/config-dir/twitter-2-kafka.config"
  restart: always

logstash2:
  image: logstash
  links:
    - kafka1
    - esearch
  volumes:
    - $PWD/logstash-config:/config-dir
  command: -f "/config-dir/kafka-2-elasticsearch.config"
  restart: always




